Feature: Register page action

Scenario: registration page for user
Given User opens the application
When Users click on the signup link
And User enter username as "rutuja25"
Then User enters firstname as "rutuja25"
Then user enterss lastname as "rajesh"
Then user enters password as "ruturajesh"
Then user enters cpwd as "ruturajesh"
Then user enters gender as "female"
Then user enters email as "rutujarajesh23@gmail.com"
Then user enters mobile as "9900092471"
Then user enters address as "bangalore"
Then user enters answer as "bangalore"
Then Message displayed Login Successfully

